import { LoginComponent } from "@/components/Login/LoginComponent";
import styles from "@/styles/Home.module.css";
import Head from "next/head";
import { useEffect, useState } from "react";

export default function Home() {
  const [isLogin, setIsLogin] = useState<boolean>(false);

  useEffect(() => {
    const userData = localStorage.getItem("user");
    console.log({ userData });
    if (userData) setIsLogin(true);
    else setIsLogin(false);
  }, []);

  useEffect(() => {
    if (isLogin) {
      //redirect to after login page
    }
  }, [isLogin]);

  return (
    <>
      <Head>
        <title>Login Redirect</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main className={styles.main}>
        <div className={styles.center}>
          <LoginComponent />
        </div>
      </main>
    </>
  );
}
